# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ce1246f445a248bd82328f772df11e755c5a0ed04ea98b08fc6450daf58f1738bda27b2ddb98b8cc42a2d83472f1ed8186bcdc53de9f8bc03c90c3b253a0119

test:
  secret_key_base: 76b12f57ad21eb75356369c53b0361a9f419117813ee2ff6ae67cceab86dbca225eb1e95434841b38ab44cdbbb47900317f5ca104a8e9fc2a9f7f056356dc30c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
