# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


# Users
  User.create(name: "Pablo", email: "pablo@pablo.com", password: "olbap", password_confirmation: "olbap")
  User.create(name: "Dina", email: "dina@dina.com", password: "anid", password_confirmation: "anid")
  User.create(name: "Aba", email: "aba@aba.com", password: "aba", password_confirmation: "aba")
  User.create(name: "Naveen", email: "naveen@naveen.com", password: "neevan", password_confirmation: "neevan")

#Genres

	alternative_rock = Genre.create(name: 'Alternative Rock')
 	ambient = Genre.create(name: 'Ambient')
 	classical = Genre.create(name: 'Classical')
 	country = Genre.create(name: 'Country')
 	dance = Genre.create(name: 'Dance')
 	deep_house = Genre.create(name: 'Deep House')
 	disco = Genre.create(name: 'Disco')
 	drum_and_bass = Genre.create(name: 'Drum & Bass')
 	dubstep = Genre.create(name: 'Dubstep')
 	electro = Genre.create(name: 'Electro')
 	electronic = Genre.create(name: 'Electronic')
 	folk = Genre.create(name: 'Folk')
 	hardcore_techno = Genre.create(name: 'Hardcore Techno')
 	hip_hop = Genre.create(name: 'Hip Hop')
 	house = Genre.create(name: 'House')
 	indie_rock = Genre.create(name: 'Indie Rock')
 	jazz = Genre.create(name: 'Jazz')
 	latin = Genre.create(name: 'Latin')
 	metal = Genre.create(name: 'Metal')
 	minimal_techno = Genre.create(name: 'Minimal Techno')
 	piano = Genre.create(name: 'Piano')
 	pop = Genre.create(name: 'Pop')
 	progressive_house = Genre.create(name: 'Progressive House')
 	punk = Genre.create(name: 'Punk')
 	r_and_b = Genre.create(name: 'R&B')
 	rap = Genre.create(name: 'Rap')
 	reggae = Genre.create(name: 'Reggae')
 	rock = Genre.create(name: 'Rock')
 	singer_songwriter = Genre.create(name: 'Singer-Songwriter')
 	soul = Genre.create(name: 'Soul')
 	tech_house = Genre.create(name: 'Tech House')
 	techno = Genre.create(name: 'Techno')
 	trance = Genre.create(name: 'Tranch')
 	trap = Genre.create(name: 'Trap')
 	trip_hop = Genre.create(name: 'Trop Hop')
 	world = Genre.create(name: 'World')

# Songs

   Song.create(title: "song1", artist: "artist1", image: "image_url1", mp3file: "mp3_url1", genre_id: alternative_rock.id)
   Song.create(title: "song2", artist: "artist2", image: "image_url2", mp3file: "mp3_url2", genre_id: ambient.id)
   Song.create(title: "song3", artist: "artist3", image: "image_url3", mp3file: "mp3_url3", genre_id: classical.id)
   Song.create(title: "song4", artist: "artist4", image: "image_url4", mp3file: "mp3_url4", genre_id: country.id)
   Song.create(title: "song5", artist: "artist5", image: "image_url5", mp3file: "mp3_url5", genre_id: dance.id)
   Song.create(title: "song6", artist: "artist6", image: "image_url6", mp3file: "mp3_url6", genre_id: deep_house.id)
   Song.create(title: "song7", artist: "artist7", image: "image_url7", mp3file: "mp3_url7", genre_id: drum_and_bass.id)
   Song.create(title: "song8", artist: "artist4", image: "image_url4", mp3file: "mp3_url4", genre_id: dubstep.id)
   Song.create(title: "song9", artist: "artist4", image: "image_url4", mp3file: "mp3_url4", genre_id: electro.id)
   Song.create(title: "song10", artist: "artist4", image: "image_url4", mp3file: "mp3_url4", genre_id: electronic.id)
   Song.create(title: "song11", artist: "artist4", image: "image_url4", mp3file: "mp3_url4", genre_id: folk.id)
   Song.create(title: "song12", artist: "artist4", image: "image_url4", mp3file: "mp3_url4", genre_id: hardcore_techno.id)
   Song.create(title: "song13", artist: "artist4", image: "image_url4", mp3file: "mp3_url4", genre_id: hip_hop.id)
   Song.create(title: "song14", artist: "artist4", image: "image_url4", mp3file: "mp3_url4", genre_id: house.id)
   Song.create(title: "song15", artist: "artist4", image: "image_url4", mp3file: "mp3_url4", genre_id: indie_rock.id)
   Song.create(title: "song16", artist: "artist4", image: "image_url4", mp3file: "mp3_url4", genre_id: jazz.id)
   Song.create(title: "song17", artist: "artist4", image: "image_url4", mp3file: "mp3_url4", genre_id: latin.id)
   Song.create(title: "song19", artist: "artist4", image: "image_url4", mp3file: "mp3_url4", genre_id: metal.id)
   Song.create(title: "song20", artist: "artist4", image: "image_url4", mp3file: "mp3_url4", genre_id: minimal_techno.id)
   Song.create(title: "song21", artist: "artist4", image: "image_url4", mp3file: "mp3_url4", genre_id: piano.id)
   Song.create(title: "song22", artist: "artist4", image: "image_url4", mp3file: "mp3_url4", genre_id: pop.id)
   Song.create(title: "song23", artist: "artist4", image: "image_url4", mp3file: "mp3_url4", genre_id: progressive_house.id)
   Song.create(title: "song24", artist: "artist4", image: "image_url4", mp3file: "mp3_url4", genre_id: punk.id)
   Song.create(title: "song25", artist: "artist4", image: "image_url4", mp3file: "mp3_url4", genre_id: r_and_b.id)
   Song.create(title: "song26", artist: "artist4", image: "image_url4", mp3file: "mp3_url4", genre_id: progressive_house.id)
   Song.create(title: "song27", artist: "artist4", image: "image_url4", mp3file: "mp3_url4", genre_id: punk.id)
   Song.create(title: "song28", artist: "artist4", image: "image_url4", mp3file: "mp3_url4", genre_id: rap.id)
   Song.create(title: "song29", artist: "artist4", image: "image_url4", mp3file: "mp3_url4", genre_id: reggae.id)
   Song.create(title: "song30", artist: "artist4", image: "image_url4", mp3file: "mp3_url4", genre_id: rock.id)
   Song.create(title: "song31", artist: "artist4", image: "image_url4", mp3file: "mp3_url4", genre_id: singer_songwriter.id)
   Song.create(title: "song32", artist: "artist4", image: "image_url4", mp3file: "mp3_url4", genre_id: soul.id)
   Song.create(title: "song33", artist: "artist4", image: "image_url4", mp3file: "mp3_url4", genre_id: tech_house.id)
   Song.create(title: "song34", artist: "artist4", image: "image_url4", mp3file: "mp3_url4", genre_id: techno.id)
   Song.create(title: "song35", artist: "artist4", image: "image_url4", mp3file: "mp3_url4", genre_id: trance.id)
   Song.create(title: "song36", artist: "artist4", image: "image_url4", mp3file: "mp3_url4", genre_id: trap.id)
   Song.create(title: "song37", artist: "artist4", image: "image_url4", mp3file: "mp3_url4", genre_id: trip_hop.id)
   Song.create(title: "song38", artist: "artist4", image: "image_url4", mp3file: "mp3_url4", genre_id: world.id)

# Playlists

   Playlist.create(title: "Favorites")
   Playlist.create(title: "Work")
   Playlist.create(title: "Fun")
   Playlist.create(title: "Weekend")
   Playlist.create(title: "Beach")
   Playlist.create(title: "Running")
   Playlist.create(title: "Gym")
   Playlist.create(title: "Gardening")
